<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <title>Document</title>
</head>
<body class="container-fluid">

     <h1 class="text-center">Liste de comptes banciares</h1>

     <table class="table table-striped table-hover">
          <tr class="table-dark">
               <th>numCompte</th>
               <th>Titulaire</th>
               <th>Solde</th>
          </tr>

          <?php foreach($comptes as $key => $value): ?>
               <tr>
                    <td> <?= $value->getReference(); ?> </td>
                    <td> <?= $value->getTitulaire(); ?> </td>
                    <td> <?= $value->getSolde(); ?> </td>
               </tr>
          <?php endforeach; ?>

     </table>

     <form action="" method="post">
          <div class="for-goup">
               <label for="">Titulaire</label>
               <select name="titulaire" id="" class="form-select">
                    <?php foreach($personnes as $key => $personne): ?>
                         <option value="<?= $personne->getId() ?>"> 
                              <?= $personne->getPrenom() ?> 
                              <?= $personne->getNom() ?>
                         </option>
                    <?php endforeach; ?>
               </select>
          </div>
          <div class="form-group">
               <label for="">Solde</label>
               <input type="text" name="solde" class="form-control">
          </div>
          <div class="mt-3">
               <input type="submit">
          </div>
     </form>


     
</body>
</html>